language: php

dist: xenial
language: c
os: linux
addons:
  apt:
    packages:
        - rabbitmq-server

services:
    - rabbitmq

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  - STOMP_PROVIDER=rabbitmq

before_script:
  - sh -c " if [ '$STOMP_PROVIDER' = 'rabbitmq' ]; then
              sudo service rabbitmq-server start;
              sudo rabbitmq-plugins enable rabbitmq_stomp;
              sudo rabbitmq-plugins list;
            fi"
  - phpize

script: ./configure && make && NO_INTERACTION=1 REPORT_EXIT_STATUS=1 make test TEST_PHP_ARGS='--show-diff'
